# Generated by Django 4.1.1 on 2024-11-02 12:42

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('viewer', '0002_movie'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movie',
            old_name='name',
            new_name='title',
        ),
        migrations.AddField(
            model_name='movie',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='movie',
            name='description',
            field=models.TextField(default=None),
        ),
        migrations.AddField(
            model_name='movie',
            name='genre',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.DO_NOTHING, to='viewer.genre'),
        ),
        migrations.AddField(
            model_name='movie',
            name='rating',
            field=models.IntegerField(default=None),
        ),
        migrations.AddField(
            model_name='movie',
            name='released',
            field=models.DateField(default=None),
        ),
    ]
