# Generated by Django 4.1.1 on 2024-11-20 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viewer', '0005_watchlist'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='image',
            field=models.ImageField(default=None, null=True, upload_to='images/'),
        ),
    ]
